#ifndef PALETTES_H_
#define PALETTES_H_
#include <FastLED.h>

DECLARE_GRADIENT_PALETTE(Rainbow_gp);

// FASTLED_NAMESPACE_END

DECLARE_GRADIENT_PALETTE(bhw4_018_gp);
DECLARE_GRADIENT_PALETTE(bhw4_057_gp);
DECLARE_GRADIENT_PALETTE(bhw4_024_gp);
DECLARE_GRADIENT_PALETTE(bhw4_048_gp);
DECLARE_GRADIENT_PALETTE(bhw1_purplered_gp);
DECLARE_GRADIENT_PALETTE(bhw1_01_gp);
DECLARE_GRADIENT_PALETTE(bhw1_04_gp);

DECLARE_GRADIENT_PALETTE(bhw1_w00t_gp);
DECLARE_GRADIENT_PALETTE(bhw2_57_gp);
DECLARE_GRADIENT_PALETTE(bhw2_51_gp);
DECLARE_GRADIENT_PALETTE(bhw2_n_gp);
DECLARE_GRADIENT_PALETTE(bhw3_52_gp);
DECLARE_GRADIENT_PALETTE(bhw3_23_gp);
DECLARE_GRADIENT_PALETTE(GMT_ocean_gp);

DECLARE_GRADIENT_PALETTE(bhw1_sunconure_gp);
DECLARE_GRADIENT_PALETTE(bhw2_22_gp);
DECLARE_GRADIENT_PALETTE(bhw2_grrrrr_gp);
DECLARE_GRADIENT_PALETTE(bhw2_turq_gp);
DECLARE_GRADIENT_PALETTE(bhw3_61_gp);
DECLARE_GRADIENT_PALETTE(bhw3_62_gp);
DECLARE_GRADIENT_PALETTE(bhw3_56_gp);
DECLARE_GRADIENT_PALETTE(purplefly_gp);

#endif